✨ 버디 등록 3회 제한 기능
SejongPeer/SejongPeer-back pull request #139
Opened 2024-03-11 07:32 UTC by rong5026

## 🌱 관련 이슈
- close #138 

## 📌 작업 내용 및 특이사항
- 쿼리로 해당 member의 Buddy 상태값이 MATCHING_COMPLETED인 Buddy 수를 가지고 버디 등록시 3회까지 제한

## 📝 참고사항
- 

## 📚 기타
-

2024-03-11 09:23 UTC, swandevson requested changes
리뷰사항 확인 부탁드립니다!

2024-03-11 09:23 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
> +	long countByMemberAndStatus(String memberId, BuddyStatus status);
`@Query` 어노테이션을 추가로 작성하신 이유가 있을까요?
위의 `countByStatusInProgressOrFoundBuddy`를 아래의 메소드처럼 status를 받고, 하나의 메소드로 통합해서 사용할 수 있지 않을까요?

2024-03-11 09:23 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +	private static final int MAX_MATCHING_COMPLETED_BUDDIES = 3;
변수 성격에 따라서도 가독성을 위해 섹션을 빈줄로 분리해주면 좋습니다
또한, 상수, 인스턴스, 생성자 순서로 작성해주시는게 좋습니다

2024-03-11 09:23 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
>  	}
당시에 확인하지 못했는데 해당 메소드를 분리하신 이유가 따로 있으실까요?
해당 메소드를 호출하는 부분에서 `budyRepository.findLastBuddyMemberId(memberId)`를 호출하는 것과 기능상 다를바가 없어보이는데 과도하게 분리해서 오히려 가독성을 떨어뜨리는 것 같습니다

2024-03-11 11:19 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
> +	long countByMemberAndStatus(String memberId, BuddyStatus status);
쿼리로 count를 하며 되겠다 생각하고 작성한거라 @Query를 사용했습니다. 
근데 jpa로 바로 memberId랑 Status값 이용해서 하면 될 것 같아요.

위의 함수를 먼저 작성하고 밑의 함수를 작성한거라 통합해서 리펙토링하는 방향으로 해보겠습니다! 피드백 감사드립니다

2024-03-11 11:21 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +	private static final int MAX_MATCHING_COMPLETED_BUDDIES = 3;
"상수, 인스턴스, 생성자 순서로 작성" 이 부분은 잘 몰랐었는데 피드백 감사합니다!

2024-03-11 11:51 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
> +	long countByMemberAndStatus(String memberId, BuddyStatus status);
위의 함수는 전체 member에 대한 특정 status의 count이고, 아래의 함수는 특정 member에 대한 특정 status의 count를 구하는 함수라 분리했습니다!

찾아보니 인자를 (String memberId, BuddyStatus status)로 설정한 후에 memberId의 값을 null로 넣으면 전체 member에 대한 상태값을 찾을 수 있다고는 하는데 차라리 분리를 해서 기능을 나누는게 좋다고 생각했습니다!

2024-03-11 12:03 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
>  	}
메소드로 분리를 안하는게 좋을 것 같네요. 복잡한 로직이 있는 것도 아니고 findLastBuddyByMemberId에서도 명확하게 어떤 기능을 하는지 나타나 있어서 수정하겟습니다!

2024-03-11 18:39 UTC, swandevson requested changes
리뷰 사항 한 번 확인하시고 답글 부탁드려요!

2024-03-11 18:39 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
>  	Long countByStatusInProgressOrFoundBuddy();
이전에 리뷰 답글에서 분리한 이유는 납득이 됩니다
하지만, 여전히 `@Query` 를 사용하고 있어 status가 변경되면 해당 구절 및 메소드 네임을 변경해야하는 수고로움이 동반되는 것 같습니다
`countByStatus`로 리네이밍하고 status를 List로 받으면 어떨까싶습니당

2024-03-12 04:36 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
>  	Long countByStatusInProgressOrFoundBuddy();
네넵 메소드 재활용면에서도 더 좋을 것 같아서 List로 넘겨주며 count 하도록 반영했습니다! 
그리고 위의 리뷰에서 메소드로 빼는 것보다는 기능도 간단하고 추후에 수정될 가능성이 적다고 생각해서 메소드로 분리를 안하는 방향으로 진행했습니다

2024-03-13 09:47 UTC, uiurihappy approved these changes
LGTM
conflict 해결해주세용

2024-03-13 11:05 UTC, merged