✨ 버디 양쪽 모두 매칭 수락 이후 모든 상대 정보 반환 기능 추가
SejongPeer/SejongPeer-back pull request #142
Opened 2024-03-11 19:20 UTC by rla124

## 🌱 관련 이슈
- close #135 

## 📌 작업 내용 및 특이사항
- 최종적인 컨트롤러의 response를 List 형식의 반환으로 수정했습니다
- 서로 다른 유저 두 명 모두가 모두 수락을 한 이후 호출되는 api라는 점을 고려해서 buddyRepository에서 한 유저에 대해 MATCHING_COMPLETED인 Buddy를 모두 찾아 list에 저장하고 
- 특정 유저의 위에서 언급한 list 내 각 버디에 대해 buddyMatchedRepository로 BuddyMatched를 찾아
- 위의 BuddyMatched에서 partner(otherBuddy)의 정보를 반환하는 로직입니다

## 📝 참고사항
- postman으로 DB에 계정 추가해서 매칭 된 버디가 한 명뿐일 때와 여러명일 때 모두 상대 유저 정보 response 확인했습니다.

## 📚 기타
-

2024-03-11 21:05 UTC, swandevson requested changes
리뷰사항 확인 부탁드립니다!

2024-03-11 21:05 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
> +	Optional<List<Buddy>> findAllByMemberIdAndStatus(String memberId, BuddyStatus status);
`findAll`메소드의 경우 조회된 결과가 없으면 빈 리스트를 반환하여 `Optional`이 의미가 없습니다.
https://velog.io/@hnsoo/JPA-%EC%9E%98%EB%AA%BB%EB%90%9C-%ED%91%9C%ED%98%84-OptionalListobject

해당 글 참고부탁드립니다!

2024-03-11 21:05 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
> +	Optional<BuddyMatched> findLatestByOwnerOrPartnerAndStatus(@Param("owner") Buddy owner);
status를 `@Query`에 고정시키지 말고 파라미터로 받아서 하는건 어떨까요?

2024-03-11 21:56 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
> +	Optional<List<Buddy>> findAllByMemberIdAndStatus(String memberId, BuddyStatus status);
BuddyRepository에서 List 반환의 경우 null이 될 수 없음을 확인했습니다! 이에 대한 예외처리는 optional이 아닌 별도로 처리할 수 있도록 코드 수정했습니다. 피드백 감사합니다.

2024-03-11 21:58 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
> +	Optional<BuddyMatched> findLatestByOwnerOrPartnerAndStatus(@Param("owner") Buddy owner);
status가 변경될 경우를 대비하여 리팩토링이 용이하게 파라미터로 받는 것이 더 좋을 것 같습니다. 수정 완료했고 postman으로 정상 작동 모두 확인하였습니다

2024-03-12 06:17 UTC, rong5026 reviewed
리뷰 남겼습니다!

2024-03-12 23:08 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
> +	Optional<BuddyMatched> findLatestByOwnerOrPartnerAndStatus(@Param("owner") Buddy owner, @Param("status") BuddyMatchedStatus status);
동의합니다. 제가 동일한 유저가 BuddyMatched에서 가질 수 있는 BuddyMatched가 버디 매칭이 여러 번 진행 될 수 있도록 확장된 것에 의해서 IN_PROGRESS와 MATCHING_COMPLETED가 양립할 수 있다는데 집중해서 위와 같이 작성했던 것 같아요. 정렬 후  LIMIT 1은 불필요한 쿼리문이었던 것 같습니다. 좋은 의견 감사합니다.

2024-03-12 23:24 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +					.orElseThrow(() -> new CustomException(ErrorCode.BUDDY_NOT_MATCHED));
MATCHING_COMPLETED와 같이 특정 상태를 이용해서 거르는 과정은 추후에 기능이 확장될 경우 또 다른 상태가 추가되거나 이름이 변경될 가능성을 염두에 두고 파리미터에 추가를 했었습니다.
하지만 기존에 제가 수락/거절 로직을 작성을 했었을 때 둘 다 수락 성공 시 양쪽의 버디들의 상태와 BuddyMatched의 상태를 동일하게 동시에 바꿨고 이 부분이 일대일 대응이면서 필요충분 조건이었던 것 같습니다. 
영환님께서 말씀해주신 부분처럼 충분히 MATCHING_COMPLETED인 Buddy만으로 충분히 BuddyMatched를 가지고 올 수 있는 것 같아요. 
더 정제된 코드를 작성할 수 있도록 피드백 주셔서 감사합니다!

2024-03-13 09:44 UTC, uiurihappy approved these changes
LGTM

2024-03-13 09:44 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
>  }
일단 approve할게용
나중에 Querydsl로 수정해주세요

2024-03-13 13:38 UTC, merged