♻️ 엔드포인트, Optional 리펙토링
SejongPeer/SejongPeer-back pull request #167
Opened 2024-03-25 09:01 UTC by rong5026

## 🌱 관련 이슈
- close #166 

## 📌 작업 내용 및 특이사항
- 버디 엔드포인트 변경
- optional 가독성 좋게 수정
- createBuddy 네이밍 create로 수정

## 📝 참고사항
- 

## 📚 기타
- 버디 엔티티 생성할 때 인자를 분리해서 넣는 방법이랑 request를 한번에 넣어서 Buddy클래스에서 처리하는 방법중에서 어떤게 더 좋을지 애매해서 일단 변경은 안했습니다!
- 버디 생성할 때 Status값을 BuddyStatus.IN_PROGRESS 이 값으로 고정해서 넣어지고 있는 상태인데, 나중에 버디생성 시 다른 Status를 가진 버디를 생성해야 할 때가 있으면 애매할 것 같아서 수정은 안했습니다!

2024-03-25 14:19 UTC, rla124 reviewed
<기타> 부분에 대한 개인적인 의견과 질문 사항입니다.
1. **외부 주입 시 통째로 넣거나 분리해서 넣기**
저는 개인적으로 서비스 단에서 버디 등록 시 빌더 메소드에 createBuddyRequest를 통째로 넣고 엔티티 단에서 세부적으로 처리하는 것이 더 좋을 것 같습니다. request를 한 번에 파리미터에 넘김으로써 코드의 간결성과 응집성이 높아질 수 있고 request가 변경되더라도 Buddy 클래스만 수정하면 되기 때문에 유지 보수에 용이할 것 같습니다. 이 부분은 다른 분들께서 피드백을 추가적으로 달아주신다면 여러 가지 의견에 대해 생각해보시면 좋을 것 같습니다.

2. **버디 생성 시 IN_PROGRESS 고정** 
나중에 버디 생성 시 "다른 Status를 가진 버디를 생성"해야 하는 부분은 어떤 점(상태)을 염두에 두신 것인지 여쭤보고 싶습니다. 유저가 버디를 신청할 때 IN_PROGRESS가 매칭 전이라는 의미를 가지고 있어서 다른 상태가 추가적으로 고려될 필요성이 있는가에 대해서 영환님게서 고민하셨던 부분이 어떤 상황인지 궁금합니다.


리뷰남기기가 안돼서 여기에 남깁니다!
2번 상태값 고정은 
return Buddy.create(
			member,
			createBuddyRequest.genderOption(),
			createBuddyRequest.classTypeOption(),
			createBuddyRequest.collegeMajorOption(),
			createBuddyRequest.gradeOption(),
			BuddyStatus.IN_PROGRESS,
			createBuddyRequest.isSubMajor()
		);
Status값을 reqeust에서 가져와 사용하는게 아니라 고정으로 사용중인데, 이후에 초기 상태값이 IN_PROGRESS이 아닌 버디를 만들어야 되는 상황이 있다면 지금처럼 request를 분리해서 넣어주는게 좋지 않을까 싶은 생각이 들어서 보류해 놨었습니다!

2024-03-26 04:48 UTC, uiurihappy reviewed
리뷰 확인해주세여

2024-03-26 04:48 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
>  		String memberId =
해당 엔드포인트가 바뀌는 거에 대해서 프론트와 논의하셨나요?
백엔드에서 바뀌면 프론트엔드도 바꿔줘야 해서요

2024-03-26 04:48 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
>  	public List<CompletedPartnerInfoResponse> getBuddyMatchedPartnerDetails() {
동일하게 의논이 필요할 듯합니다.

2024-03-26 07:34 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
>  		String memberId =
아직 논의는 안된 상태라 pr 병합하기 전에 한번 여쭤보려고 했습니다! 지금 바로 여쭤보는게 좋을 것 같네요

2024-04-03 02:45 UTC, swandevson requested changes
리뷰 확인부탁드립니다!

2024-04-03 02:45 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
>  			return null;
한 줄이라도 중괄호 써주세용

2024-04-03 02:45 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
> +		Optional<Honbab> optionalHonbab = getLastestHonbabByMemberId(memberId);
해당 부분도 `.orElse(null)`로 리팩토링할 수 있지 않을까요?

2024-04-04 08:55 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
> +		Optional<Honbab> optionalHonbab = getLastestHonbabByMemberId(memberId);
네넵 리펙토링하겠습니다

2024-04-08 09:22 UTC, uiurihappy approved these changes
LGTM

2024-04-11 12:23 UTC, rla124 approved these changes
머지하셔도 좋을 것 같습니다!

2024-04-11 15:23 UTC, swandevson approved these changes
변경내역 확인했습니다!

2024-04-12 08:54 UTC, merged