✨ 단과대 별 개설된 수업 정보 조회
SejongPeer/SejongPeer-back pull request #180
Opened 2024-04-05 10:01 UTC by rla124

## 🌱 관련 이슈
- close #179 

## 📌 작업 내용 및 특이사항
- 피그마 상에서 학교 수업 명을 기준으로 스터디를 찾는 기능이 있어서 단과대 조회 api는 이미 있기 때문에 단과대별로 선택해서 수업 내역을 확인할 수 있는 API 입니다.

## 📝 참고사항
- 

## 📚 기타
-

2024-04-06 07:51 UTC, swandevson requested changes
리뷰 달아드린 부분들 엔티티에도 적용해주심 감사하겠습니당

2024-04-06 07:51 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/college/api/CollegeLessonProfController.java
> +}
`Lesson`보다는 `Lecture`라는 네이밍이 더 적절할 것 같습니다
추가로, `prof`는 제외하고 `Lecture`로만 표현해도 괜찮지 않을까 싶습니다. 필드를 `name`, `profressor`으로 했을 때 충분히 전달될 것 같습니다.

2024-04-06 07:51 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeLessonProf.java
> +	private String prof;
축약하지 않고 `professor`로 쓰는 것이 좋을 것 같습니다.

2024-04-06 10:28 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/college/api/CollegeLessonProfController.java
> +}
리뷰 주신 부분은 스터디 엔티티 PR이 머지되고 다시 Lecture 테이블에 수강 편람 수업 정보 넣어서 수정하도록 할게요

2024-04-09 06:31 UTC, rong5026 reviewed
리뷰 한번만 확인해주세요! 수고하셨습니다

2024-04-09 06:31 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeLessonProf.java
> +public class CollegeLessonProf {
테이블 명명 규칙 찾아보니깐 '-' 쓰는건 다들 별로 추천을 안하는 것 같아요
https://www.codeit.kr/community/questions/UXVlc3Rpb246NjA0OWZkNWJhYzVkM2U0YjY0OTkxN2Q2
저가 찾아본 글 링크 걸어드립니다!

2024-04-09 06:44 UTC, uiurihappy reviewed
리뷰 확인해주세여

2024-04-09 06:44 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeLessonProf.java
> +public class CollegeLessonProf {
저도 이에 대해 동감하는 부분이에요
`@Table` 어노테이션을 굳이 사용 안해도 CollegeLessonProfessorRelations라 명명해도
college_lesson_professor_relations으로 저장되니 CollegeLessonProfessorRelations로 수정해도 좋을듯합니다:)

2024-04-09 06:44 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeLessonProfService.java
> +		return Collections.unmodifiableList(lessonInfo);
```java
List<CollegeLessonProf> collegeLessonProfs = collegeLessonProfRepository.findAllByCollege(college);
List<CollegeLessonProfResponse> lessonInfo = collegeLessonProfs.stream()
    .map(CollegeLessonProfResponse::from)
    .toList();
return Collections.unmodifiableList(lessonInfo);
```
이렇게 수정해보시는 건 어떨까요??

List<Entity> -> List<DTO>로 변환하기 전 데이터에 대한 수정작업이 이루어 지게 될 경우 Service 레이어에서 수정이 용이할 거 같아요

만약 변환 후 작업이 이뤄진다면 DTO 클래스에서 수정이 이뤄져야 할 듯하네요

2024-04-09 08:16 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeLessonProf.java
> +public class CollegeLessonProf {
넵! 피드백 감사드립니다~

2024-04-09 08:27 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeLessonProfService.java
> +		return Collections.unmodifiableList(lessonInfo);
말씀해주신 것처럼 List<CollegeLessonProf> collegeLessonProfs 변수로 받아서 한 번 거치면 데이터 수정 가능성도 고려할 수 있을 것 같아요 
피드백 감사합니다!

2024-05-01 06:11 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeLessonProf.java
> +	private String prof;
lecture 엔티티에 시간표 정보 다시 넣고 dto와 필드 모두 professor로 표기하도록 수정했습니다.

2024-05-07 12:53 UTC, swandevson requested changes
리뷰 확인 부탁드립니당

2024-05-09 14:41 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/lecturestudy/controller/LectureController.java
> +	private final LectureService lessonProfService;
놓쳤네요.. 확인해주셔서 감사합니다!

2024-05-09 14:56 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/lecturestudy/service/LectureService.java
> +		return Collections.unmodifiableList(lessonInfo);
`collect(Collectors.toList())` 이 부분이 stream의 최종 연산이기 때문에 가독성을 높일 수 있고 unmodifiableList로 바뀌기 전에 lessionInfo 리스트가 수정될 가능성을 염두하였었습니다. 그런데 사실상 수강 편람 데이터를 별도로 수정하 않는 이상 말씀해주신 것처럼 stream을 한번에 return하는 것이 더 좋을 것 같습니다. stream을 바로 return하되 unmodifiableList로 감싸서 return하는 방향으로 수정했습니다.

2024-05-14 00:26 UTC, merged