✨스터디 게시글 무한 스크롤 전체 조회, 단건 상세 조회, 게시글 다중 조건 검색 API
SejongPeer/SejongPeer-back pull request #190
Opened 2024-05-19 03:18 UTC by rla124

## 🌱 관련 이슈
- close #189 

## 📌 작업 내용 및 특이사항
- 6개월 단위의 전체 게시글 무한 스크롤 기능 구현
- 게시글 상세 조회(글쓴이 전공, 닉네임 등 포함)
- 게시글 다중 조건 검색 

## 📝 참고사항
- Lecture 엔티티가 BaseEntity를 상속 받고 있어 "0000-00-00 00:..." 이렇게 초기화가 되어  created_at 칼럼이 추가가 되었는데 이 부분이 jpa mapping 오류(500 error)를 유발하고 실제 필요가 없는 칼럼이므로 삭제

## 📚 기타
-

2024-05-23 06:34 UTC, uiurihappy reviewed
리뷰 확인해주세요!

2024-05-23 06:34 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/Lecture.java
수환님 PR도 동일하게 BaseEntity 삭제하는 코드가 있어서 혹시나 충돌이 있을 수 있으니
주의해서 머지해주세요!

2024-05-23 06:34 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/lecturestudy/repository/LectureStudyRepository.java
> +}
```
Optional<LectureStudy> findByStudy(Study study);
```
이렇게는 어떨까요? 프록시 객체로 인자를 받아 조회할 수도 있어서 굳이 id로 조회하지 않아도 되는걸로 알고 있어요!

ExternalActivityStudyRepository에도 확인부탁드릴게용

2024-05-23 12:41 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/Lecture.java
네~ 만약 수환님 PR이 먼저 머지된다면 충돌 해결하겠습니다~

2024-05-24 02:16 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/Lecture.java
저도 확인했습니당

2024-05-24 02:43 UTC, swandevson requested changes
리뷰 확인해주세용

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudySearchRequest.java
> +	@Schema(description = "모집 최대 인원") Integer recruitmentMax,
`@NotBlank`보다는 `@NotNull`이 적절할 것 같습니다! (NotBlank는 String 한정으로 알고 있습니다)
뿐만 아니라 각각 `@Min` 또는 `@Max`가 필요할 것 같습니다!
또한, controller나 service 레이어에서 min > max인 요청이 들어오지 않는지 검증하는 로직도 필요할 것 같습니당

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
> +
아래에 `/post/{studyId}`로 단건조회가 이미 있으니, 전체 조회는 `/post`만 쓰셔도 좋을 것 같습니다!

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
> +
또한, 현재 모든 엔드포인트가 `~/post`로 시작되는데 requset mapping에 post를 추가하는 방향은 어떠실까요?

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
> +		);
study에서 member를 추출할 수 있는데 외부에서 member를 별개로 주입받는 이유가 있으실까요?

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +	private static final String EXTERNAL_ACTIVITY_STUDY = "수업외활동";
이전(1월 26일)에 윤범님이 작업하신 `StudyType` enum이 이미 있는데 따로 선언하신 이유가 있으실까요?

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +	private static final String EXTERNAL_ACTIVITY_STUDY = "수업외활동";
만약 enum을 사용하는 방향으로 수정하신다면 제 pr확인 후 수정 혹은 pull해서 반영해주세요!

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +	public Slice<StudyTotalPostResponse> getAllStudyPost(String choice, int page) {
코드로 볼 때 `choice`는 학교수업 스터디 또는 대외활동 중 하나를 선택하는 것 같은데, 외부에서 enum으로 받아오는게 낫지 않을까요? 앞선 리뷰에서처럼용
또한, choice라는 네이밍도 너무 모호하게 느껴집니다 ㅜ studyType같은 표현으로 대체하는건 어떠실까요?

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +		spec = spec.or(StudySpecification.equalsContent(request.searchWord()));
spec를 계속 재할당하지 않고 메서드 체이닝하는 방법은 불가능한걸까요??

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
> +	}
`getAllPostBySearch` 보다 `searchPosts` 또는 `searchAllPost`가 더 좋을 것 같습니다

2024-05-24 02:43 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +			.collect(Collectors.toList());
해당 레이어에서 추가 작업이 이루어지지 않을 뿐더러, 외부에서 변경작업이 없는데 `toList()` 쓰신 이유가 있으실까요?
이전에도 말씀드렸다싶이 별 이유가 없으면 수정 불가능한 리스트로 만들어주세요!

2024-05-24 06:46 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/lecturestudy/repository/LectureStudyRepository.java
> +}
Study로 바로 받으니까 더 간결해지네요 피드백 감사합니다!

2024-05-24 07:15 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudySearchRequest.java
> +	@Schema(description = "모집 최대 인원") Integer recruitmentMax,
StudySearchRequest 관련 유효성 검증, 예외 처리 피드백 주셔서 감사합니다! @Valid가 검색어 string 형식을 제외하고 @NotBlank를 쓰면 500에러를 터뜨리네요

2024-05-24 07:23 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
> +
넵 이전 버전의 스터디 게시글 crud의 엔드포인트와 구별하려고 /post를 붙였는데 관련 request record에 post 추가하겠습니다

2024-05-24 07:33 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
> +		);
말씀하신 것처럼 제가 게시글 단건 상세 조회에서 memberUtil로 service에서 주입을 받아서 response record 정적 메소드로 넘겨주었는데 원래 게시글 작성자의 member 정보를 반환해야 하는데 저는 로그인한 유저의 정보를 반환하는 로직을 짰던 것 같습니다. 이 피드백을 보고 로직 설계가 잘못된 것을 파악하고 수정했네요.. 감사합니다!

2024-05-24 07:50 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +	private static final String EXTERNAL_ACTIVITY_STUDY = "수업외활동";
StudyType 확인했었는데 피그마 상에서 저희 메인 페이지 세종 스터디 항목에 좌측에 "학교 수업 스터디", 우측에 "수업 외 활동"이 있어서 상수처리를 했었씁니다. enum으로 통일하겠습니다

2024-05-24 08:12 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +	public Slice<StudyTotalPostResponse> getAllStudyPost(String choice, int page) {
예전에 버디 수락/거절에서는 ACEPT, REJECT를 enum으로 받는 것보다 boolean을 추천해주셨는데 이 부분은 enum 적용이 저도 더 좋은 것 같습니다~

2024-05-24 08:30 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +		spec = spec.or(StudySpecification.equalsContent(request.searchWord()));
넵 추가적으로  "or" 부분도 따로 한번에 처리하는 메소드로 리펙토링하고 지금처럼 JPA Creteria API도 메소드 체이닝이 가능해서 적용했습니다 감사합니다~

2024-05-24 10:27 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudySpecification.java
> +
Specification을 처음 봤는데 이렇게 쿼리날리면 코드가 더 깔끔한 것 같네요. 덕분에 새로운거 알아갑ㄴ디ㅏ!

2024-05-24 10:30 UTC, rong5026 approved these changes
수고하셨어요!

2024-05-24 10:31 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudySpecification.java
> +
감사합니다~

2024-05-25 11:55 UTC, merged