Feature/#191 스터디 조기마감
SejongPeer/SejongPeer-back pull request #192
Opened 2024-05-19 08:45 UTC by rong5026

## 🌱 관련 이슈
- close #191 

## 📌 작업 내용 및 특이사항
- 스터디 모집 중 조기마감
- 승인된 유저에게는 카카오톡 링크방 문자로 전송
- 승인이 안된 유저의 상태값들은 전부 REJECT로 변경

## 📝 참고사항
- 

## 📚 기타
-

2024-05-19 09:00 UTC, uiurihappy approved these changes
리뷰 확인해주세용

2024-05-19 16:22 UTC, swandevson requested changes
리뷰 확인 부탁드립니당

2024-05-19 16:22 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
> +
`POST` 방식에서 쿼리스트링을 사용하는건 RESTful하지 못하기 때문에 Body로 받으셔야 할 것 같습니다!

2024-05-24 02:25 UTC, rla124 approved these changes
PR 확인했습니다! 수고 많으셨어요

2024-05-24 02:25 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
> +
필요 없을 수도 있겠지만 이 부분에서 프론트에서 잘못된 studyId로 스터디 조기마감 요청이 들어왔을 경우 404 not found 예외처리가 있어도 좋을 것 같습니다.

2024-05-24 07:07 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
> +
네이밍 고민하다가 빼먹었네요.. 바로 수정하겠습니다! body로 받는 부분도 수정하겠습니다!

2024-05-24 07:13 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
> +
예외처리가 필요할 것 같네요 추가하겠습니다!

2024-05-25 17:32 UTC, swandevson approved these changes
리뷰 수정 사항 확인했습니다
고생하셨습니당

2024-07-10 06:06 UTC, closed without merging