✨ feat: 스터디 CRUD 1차 구현
SejongPeer/SejongPeer-back pull request #26
Opened 2024-02-06 09:21 UTC by uiurihappy

## 🌱 관련 이슈
- close #23 

## 📌 작업 내용 및 특이사항
- 스터디 CRUD로, 리스트 조회, 단건 생성,조회,수정,삭제 API 간단하게 구현하였습니다
- 나중에 SecurityContext에서 가져오는 member.getId()를 불러오는 Feature 추가 시, 수정 작업하겠습니다!

## 📝 참고사항
- 

## 📚 기타
-

2024-02-06 14:09 UTC, HaiSeong reviewed
고생하셨습니다!
QueryDsl로 페이징 하는 부분 코드 보면서 어떤식으로 쓰는건지 대충 감을 잡을 수 있었습니다.
몇가지 궁굼하거나 추가되었으면 하는 의견 남겼습니다!

2024-02-06 14:09 UTC, HaiSeong commented on src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
> +    private Long id;
![image](https://github.com/SejongPeer/SejongPeer-back/assets/58177929/691f2243-9586-4366-91a9-9258555b923b)

erd 설계할때 study id를 uuid로 저장하기로 했었는데 제가 저번 코드리뷰에서 확인하지 못한것 같습니다.

2024-02-06 14:09 UTC, HaiSeong commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +    }
`@Transactional(readOnly = true)` 옵션을 `findOneStudy`, `findSliceStudy` 메서드에 적용하면 성능 최적화를 얻을 수 있지 않을까 의견 드립니다.

2024-02-06 14:09 UTC, HaiSeong commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +    }
36라인 `LocalDateTime recruitmentStartAt = LocalDateTime.now();`  이 부분에서 선언한 변수가 사용되지 않고 있는데 특별한 역할을 하는 줄인지 궁금합니다!

2024-02-06 18:58 UTC, swandevson requested changes

2024-02-06 18:58 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +    public Slice<StudyFindResponse> findSliceStudy(int size, Long lastId) {
상단의 `findOneStudy` 메소드와 함께 읽기 전용 메소드처럼 보이는 readOnly 옵션값 true 있으면 좋을 것 같습니다!

2024-02-06 19:01 UTC, swandevson approved these changes
해성님이 리뷰를 잘 남겨주셔서 제가 첨언할 부분이 없는 것 같습니다
고생하셨습니다!

2024-02-07 01:45 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
> +    private Long id;
그렇네요.. 그럼 수정하고 createdAt으로 desc 걸어서 최근 생성일자로 정렬하도록 하겠습니당

2024-02-07 01:46 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +    }
깜빡했네요.. 메서드 전체에 `@Trasactional`을 걸어놓고 놓쳤습니다

2024-02-07 01:47 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
> +    }
모집 시작기간이 혹시나 없을 경우 now()을 넣어 대입하려했는데 지금은 기획상 없어도 될 거 같네요
삭제할게요!

2024-02-07 03:31 UTC, swandevson approved these changes

2024-02-07 15:15 UTC, HaiSeong approved these changes

2024-02-08 00:01 UTC, merged