✨ 회원 URD 구현
SejongPeer/SejongPeer-back pull request #27
Opened 2024-02-07 22:36 UTC by swandevson

## 🌱 관련 이슈
- #22 

## 📌 작업 내용 및 특이사항
-

## 📝 참고사항
- 

## 📚 기타
-

2024-02-08 06:03 UTC, uiurihappy requested changes
리뷰 달았습니다!
저희가 전체적으로 findBy나 중복 케이스 등 백엔드 내부에서 statusCode 컨벤션을 약속하지 않았었네요.. 한번 얘기해보는 것도 좋을 듯합니다

2024-02-08 06:03 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
> +
JwtAuthenticationFilter와 WebSecurityConfig에서 EXCLUDE_URLS을 동일하게 사용한다면 constant 패키지에 클래스를 생성해서 진행해도 좋을 거 같아요:)

2024-02-09 03:42 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
>  @RestController
현재 이슈에 반영해서 같이 commit 올리도록 하겠습니다!

2024-02-09 06:03 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
> +    DUPLICATED_ACCOUNT(HttpStatus.BAD_REQUEST, "이미 존재하는 계정입니다."),
저도 찾아보니 409가 보편적이네요! 변경하겠습니당

2024-02-09 06:18 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
>  @RestController
merge후 변경하겠습니다!

2024-02-13 04:15 UTC, uiurihappy approved these changes
LGTM
일단 이대로 머지하고 추후 고민 좀 더 해보다가
리팩토링 해야겠슴다

2024-02-15 02:44 UTC, merged