Feature/#37 buddy entity 추가
SejongPeer/SejongPeer-back pull request #38
Opened 2024-02-20 13:32 UTC by rong5026

## 🌱 관련 이슈
- close #

## 📌 작업 내용 및 특이사항
- buddy 엔티티, buddymatched 엔티티 생성

## 📝 참고사항
- 버디 enum 설정할 때 SearchStatus의 값을 정확하게 어떤 값으로 해야할지 몰라서 IN_PROGRESS("찾는 중"),
	FOUND_BUDDY("찾음"); 이 2가지로 일단 설정해 놨습니다.

## 📚 기타
-

2024-02-20 13:55 UTC, swandevson requested changes
엔티티에 남겨놓은 사항들 type도 같이 수정해주세요!

2024-02-20 13:55 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
> +	@Builder
`createBuddy`처럼 팩토리 메소드를 사용하시는거라면 Builder의 접근제한자도 `private`로 변경해주세요

2024-02-20 13:55 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/type/GenderOption.java
> +	NONE("다른 성별");
'다른 성별'이 아닌 '상관없음'입니다

2024-02-20 14:19 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
> +	private MatchingStatus matchingStatus;
ERD보면서 굳이 search_status가 필요한지 긴가민가 하고 있었는데 status 하나로 가는게 맞는 것 같아요. MachingStatus에서 Found_BUDDY만 추가하고 searchState는 삭제하도록 하겠습니다!

2024-02-20 14:32 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
> +	@Builder
네넵 확인했습니다!

2024-02-20 15:11 UTC, uiurihappy requested changes
수정부탁드립니다:)

2024-02-20 15:11 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
> +	private MatchingStatus matchingStatus;
해당 부분은 이미 Enum 타입이 정의되어 있어서 nullable false만 해주셔도 될 거 같아용

2024-02-20 15:11 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
> +	private Member member;
명확히 알기 위해 name = "member_id"로 해주세용

2024-02-20 15:11 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/BuddyMatched.java
> +
buddyId1과 buddyId2는 무슨 의미를 가지고 있는 지 알 수 있을까요??
통하는 의미가 있다면 buddy1, buddy2 보단
신청자 source
받는 사람 target으로 하듯이 변수명을 써줬으면 좋겠어용

2024-02-20 17:51 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/BuddyMatched.java
> +
@uiurihappy 서로 조건이 맞아 매칭된 버디를 뜻합니다!
저도 처음엔 source, target처럼 구분지어서 작성할까 고민했는데, 매칭이 단방향이 아닌 양방향으로 이루어져서 뭔가 의미있는 변수 쓰기가 조금 애매한 것 같습니다 ㅜ

2024-02-20 17:54 UTC, swandevson requested changes

2024-02-20 17:54 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
> +	@Column(columnDefinition = "enum('GRADE_1', 'GRADE_2', 'GRADE_3', 'GRADE_4', 'NONE')", nullable = false)
전 리뷰에도 달았듯이 `NONE`은 '상관없음'이 아닌 '존재하지 않음'의 의미가 더 강하므로 변경해주세요

이하 BuddyRange, BuddyType, GradeOption의 enum들도 포함입니다!

2024-02-21 02:58 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
> +	private MatchingStatus matchingStatus;
네넵

2024-02-21 03:04 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/BuddyMatched.java
> +
아 저가 실수로 빼먹었네요.. BuddyMatched에도 매칭상태가 있어야합니다! 수정해놓을게요

2024-02-21 03:21 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
> +	@Column(columnDefinition = "enum('GRADE_1', 'GRADE_2', 'GRADE_3', 'GRADE_4', 'NONE')", nullable = false)
전부 변경하였습니다!

2024-02-21 03:30 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
> +	@Column(columnDefinition = "enum('COLLEGE', 'DEPARTMENT', 'SAME_COLLEGE', 'SAME_DEPARTMENT', 'ALL')", nullable = false)
버디 범위로는   같은 학과 , 같은 단과대, 상관없음  이렇게 3가지로 하면 될 것 같습니다
ERD에서는 학과, 같은학과를 구분해있어서 저런식으로 했습니다!

2024-02-21 07:01 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/BuddyMatched.java
> +
아하 짝을 찾는 사람과, 짝이 된 사람의 구분 말씀하신거군요
코드상에서는 'me', 'partner'로 각각 구분지은 것처럼 컬럼도 구분 짓는게 더 좋겠네용

2024-02-21 07:02 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
>      @Builder
버디와 회원은 일대일 하기로 했지 않았었나요??

2024-02-21 07:05 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
>      @Builder
ERD CLOUD상에 1:N으로 되어있고, 회원 한 명이 여러번 버디를 신청할 수 있는 경우(ex. 거절 당함, 짝을 찾기 전 매칭 취소)도 있어 1:N이 맞을 것 같습니당

2024-02-21 07:09 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
>      @Builder
마지막 상태를 확인해서 매칭을 거절했을 경우 패널티 적용하는것 때문에 1:n으로 했어요!

2024-02-21 08:26 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/BuddyMatched.java
> +
owner, partner로 구분시키도록 하겠습니다! 짝을 찾는 사람을 owner, 짝이 된 사람을 partner로 하겠습니다.

2024-02-21 09:02 UTC, rla124 approved these changes

2024-02-21 09:03 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/BuddyMatched.java
> +
확인했습니다~

2024-02-21 10:36 UTC, merged