Feature/#41
SejongPeer/SejongPeer-back pull request #48
Opened 2024-02-21 17:00 UTC by rong5026

## 🌱 관련 이슈
- close #

## 📌 작업 내용 및 특이사항
- Buddy 등록기능

## 📝 참고사항
- 사용자의 고유 id를 받아오는 부분에서
(String) SecurityContextHolder.getContext().getAuthentication().getPrincipal();  이 값으로 받아오면 되는지 확인 부탁드립니다!

## 📚 기타
-

2024-02-22 04:08 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +	}
나중에 CustomException을 만들어 놓으신걸 보고 한번 써보면 좋겠다 싶어서 했는데 중복으로 체크가 되게했네요. 
이미 Valid에서 null값을 체크해서 더 함수 부분은 필요없을 것 같습니다!. 피드백 감사합니다!

2024-02-22 05:53 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
엔티티가 buddy라는 걸 나타내는데 
type, range 등 앞에 buddy를 붙일 필요는 없는 거 같은 데 어떻게 생각하시나요??

2024-02-22 09:21 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java
그리고 range도 figma에 UI를 살펴보니깐 
선택사항이 학부의 종류 ( 학과, 단과대, 상관없음 ) 이렇게 3가지 중 하나를 선택하는것 같아서
범위라는 "range" 네이밍을 학부라는 의미인 "department"로 바꾸면 어떨지 다른 분들의 의견을 듣고 싶습니다!

2024-02-22 19:20 UTC, rla124 approved these changes
구현하신 부분 모두 확인 완료했습니다! pr 올리신 구현 코드가 제 파트에서도 필요해서 머지해주시면 감사드리겠습니다

2024-02-23 05:00 UTC, swandevson requested changes
제가 확인하지 못하고 넘어간 부분이 있었네요
반영 부탁드립니다!

2024-02-23 05:09 UTC, uiurihappy requested changes

2024-02-23 05:09 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
> +	}
메서드 명에서는 명확하게 buddyRegister라는 네이밍은 어떠실까요?
간혹 service 레이어에서 static import를 하거나 다른 도메인과 중복되는 네이밍이 겹치면 혼동이 올 거 같아용

2024-02-23 05:09 UTC, uiurihappy commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +		Member member =
위 리뷰와 동일하게 여기는 registerBuddy로 하여 네이밍을 하는 게 나을듯합니당

2024-02-23 05:09 UTC, uiurihappy commented
develop 브랜치 merge 하시고 push 부탁드릴게요:)

2024-02-23 05:19 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +				.orElseThrow(() -> new CustomException(ErrorCode.INTERNAL_SERVER_ERROR));
네넵 수정하도록 하겠습니다

2024-02-23 05:25 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +		Member member =
네넵 총합해서 병합하겠습니다

2024-02-23 05:45 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
> +	}
네넵 피드백 감사합니다!

2024-02-23 05:58 UTC, merged