Feature/#52
SejongPeer/SejongPeer-back pull request #55
Opened 2024-02-23 16:34 UTC by rong5026

## 🌱 관련 이슈
- #52 

## 📌 작업 내용 및 특이사항
- 버디 매칭 전 취소 기능
- In_Progress 상태일 때만 취소, 다른 경우는 예외

## 📝 참고사항
- 

## 📚 기타
-

2024-02-23 22:53 UTC, swandevson requested changes
요청사항 확인 후 코멘트 및 반영 부탁드립니다!

2024-02-23 22:53 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
> +		buddyService.cancelBuddy(memberId);
`cancel`이라는 단어에 명사보다는 행위가 함께 오는게 더 어울릴 것 같습니다
`cancelBuddyMatching`으로 리네이밍 하시는건 어떨까요??

2024-02-23 22:53 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
> +	Optional<Buddy> findLastBuddyByMemberId(@Param("memberId") String memberId);
최근 정보 하나만 조회한다면 LIMIT 1 조건을 거는게 좋을 것 같습니다

2024-02-23 22:53 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +		}
if-else문 보다는 guard clause로 작성해주시는게 좋아보입니다

https://nhj12311.tistory.com/617
해당 글 참조해주세용

2024-02-23 22:53 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +		return buddyOptional.orElseThrow(() -> new CustomException(ErrorCode.BUDDY_NOT_FOUND));
Optional 객체로 한 번 받고 처리할게 아니라, 바로 예외처리 하는 건 어떠실까요??

2024-02-24 06:25 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
> +	Optional<Buddy> findLastBuddyByMemberId(@Param("memberId") String memberId);
네넵 수정했습니다!

2024-02-24 06:27 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
> +		buddyService.cancelBuddy(memberId);
Service에서도 registerBuddy가 있어서 buddyRegister로 했었는데 Controller에서나 Service에서나 둘다 같은 네이밍으로 가는게 좋을까요??

2024-02-24 06:33 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +		return buddyOptional.orElseThrow(() -> new CustomException(ErrorCode.BUDDY_NOT_FOUND));
지금 이전코드와 조금 수정된 부분이 있어서 buddyOptional이 null일때 예외를 던지는게 아니라 null이 아닐때만 조건에 걸리도록 로직을 바꾸어서 일단 Optional을 사용했습니다!

2024-02-24 15:17 UTC, uiurihappy approved these changes
LGTM

2024-02-24 15:36 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +		}
네넵 수정했습니다!

2024-02-24 15:46 UTC, merged

2024-02-24 17:36 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
> +		buddyService.cancelBuddy(memberId);
controller와 service는 확실하게 레이어가 나눠져있기 때문에 같아도 문제없을 것 같습니다
또한, 함수는 동사로 시작하는게 일반적인 네이밍 규칙입니다!