✨ 버디 매칭 상테 업데이트 및 매칭 거절 유저에 대한 패널티 부여
SejongPeer/SejongPeer-back pull request #59
Opened 2024-02-24 07:07 UTC by rla124

## 🌱 관련 이슈
- close #40 

## 📌 작업 내용 및 특이사항
- BuddyMathced 엔티티의 매칭 상태를 업데이트합니다
- 짝 매칭이 되었으나 거절한 유저는 버디 신청을 못하도록 합니다

## 📝 참고사항
- 상대방(버디) 정보를 알지 못해도 SecurityContextHolder에서 유저 정보를 가져와서 BuddyMatched 엔티티에서 상대 버디 정보를 찾는 방식으로 구현하고자 하였습니다.

## 📚 기타
-

2024-02-24 19:37 UTC, swandevson requested changes
전체적으로 코드를 살펴봤을 때 `BuddyMatched`에 `Buddy`가 따로따로 들어오는 것으로 이해하신 듯한 코드가 보입니다
재차 말씀드리지만 **`BuddyMatched`는 매칭 짝을 찾았을 때  한 번에 생기겁니다!!!**  제가 작성한 버디 매칭 부분을 확인해보시면 충분히 이해하실 수 있을 것이라 생각합니다
이 부분 유의해서 리뷰 남겨드린 부분 뿐만 아니라, 전체적인 코드 수정 부탁드립니다

2024-02-24 19:37 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
> +	Optional<BuddyMatched> findByOwnerOrPartner(@Param("owner") Buddy owner);
가장 최근 건 중 하나를 불러와야 하지 않을까요??
만약, 이전에 매칭을 거절한 이력이 있는데  또 동일한 사람끼리 매칭되는 경우도 고려해야 할 것 같습니다

2024-02-24 19:37 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +	}
`BuddyMatched` 엔티티는 매칭 짝을 찾았을 때 생성됩니다
때문에, 해당 메소드에서 `existingMatch`가 없을 때 엔티티를 생성하는 것은 잘못된 로직입니다. `exisitngMatch`가 없을 경우 예외처리하는 것이 좋아보입니다

2024-02-24 19:37 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +		if (ownerBuddy != null && targetBuddy != null) {
둘 다 null이 아닐 때 로직을 넣는 것 보다, 둘 중 하나라도 null일때 예외처리하는 것이 가독성 측면에서 좋아보입니다 (guard cluase)

2024-02-24 19:37 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +				status = BuddyMatchedStatus.MATCHING_FAIL;
재차 말씀드리지만 중도 취소 상태인 `CANCELED`는 짝을 찾기 전입니다. 즉, BuddyMatched 엔티티가 생성되기 전입니다.
때문에 `CANCELED` 상태일 때 `BuddyMatched` 상태를 변경한다는 상황 자체가 모순적입니다. 수정해주세요!

2024-02-24 19:37 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +				status = BuddyMatchedStatus.IN_PROGRESS;
최초 상태인 `IN_PROGRESS`는 BuddyMatched가 생성될때만 할당되어야 합니다.
해당 분기로 인해 혹시나 상태가 변경될 수 있는 상황이 생길 수 있으니 삭제하는 것이 좋아보입니다

2024-02-24 19:37 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +			buddyMatched.setBuddyMatchedStatus(BuddyMatchedStatus.MATCHING_FAIL);
`BuddyMatched`에 `owner`와 `target`은 무조건 존재합니다. 때문에 둘 중 하나라도 null일때 buddyMatched를 조작하는 일은 있을 수가 없습니다

2024-02-24 19:37 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			.orElse(null);
`orElseThrow`가 아닌 `orElse(null)`인 이유가 따로 있으실까요?

2024-02-24 19:37 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
> +	REJECT_PENALTY(HttpStatus.FORBIDDEN, "짝매칭 이후 거절한 유저는 버디를 등록할 수 없습니다.");
'일정시간 동안' 추가할 수 없다는 문구로 수정되면 더욱 좋을 것 같습니다

2024-02-24 19:37 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			latestBuddy.getUpdatedAt().isAfter(LocalDateTime.now().minusHours(1))) {
현재 작성한 조건인 '현재로부터의 1시간 전보다 마지막 업데이트가 더 이후 시간이다 ' 보다는 '마지막으로 업데이트로 부터 한 시간이 지나지 않았다'가 좀 더 가독성있을 것 같습니다.

사람마다 다를 수 있겠지만 전 해당 부분에서 헷갈려서 5분 정도 써가면서 비교했습니다 ㅜㅜ

2024-02-25 16:02 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyMatchingController.java
> +	}
반영 완료했습니다

2024-02-25 16:03 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +	}
리뷰에도 적어주셨듯이 제가 이해를 잘못된 방향으로 하고 있었던 점을 명확하게 짚어주셔서 감사드립니다. develop에 머지 이후 작성하신 BuddyMatched 생성 코드를 통해 다시 수정하였습니다.

2024-02-25 16:06 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +		if (ownerBuddy != null && targetBuddy != null) {
예외 처리 부분은 해당 함수 밖으로 빼서 처리하고 guard cluase를 적용하여 중첩 조건문을 없애는 depth가 얕아지는 방식으로 수정하였습니다.

2024-02-25 16:08 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +				status = BuddyMatchedStatus.MATCHING_FAIL;
BuddyMatched가 생성된 이후 짝 수락, 거절에 대한 dto를 받은 이후 수행하는 로직으로 변경하였습니다. canceled 상태일 때 BuddyMatched 상태를 변경한다는 것이 모순된 상황임을 확인하였습니다.

2024-02-25 16:09 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +				status = BuddyMatchedStatus.IN_PROGRESS;
BuddyMatched를 IN_PROGRESS로 설정하는 부분은 매칭 스케쥴러를 통해 확인하였고 이 상태로 초기화하는 부분은 삭제하였습니다.

2024-02-25 16:13 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			.orElse(null);
null보다는 orElseThrow 예외 처리를 하는 방향이 더 적합한 것 같아 수정 완료하였습니다.

2024-02-25 16:16 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +			buddyMatched.setBuddyMatchedStatus(BuddyMatchedStatus.MATCHING_FAIL);
BuddyMatched의 상태는 ownerLatestBuddy와 targetBuddy가 모두 null이 아닐 때만 업데이트 되도록 수정하였습니다.

2024-02-25 16:29 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
> +	Optional<BuddyMatched> findByOwnerOrPartner(@Param("owner") Buddy owner);
매칭된 BuddyMatched 중에서 최근에 생성된 것을 찾을 수 있도록 id를 기준으로 쿼리문을 작성하는 방식으로 수정하였습니다.

2024-02-25 16:58 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			latestBuddy.getUpdatedAt().isAfter(LocalDateTime.now().minusHours(1))) {
`latestBuddy.getUpdatedAt().plusHours(1).isAfter(LocalDateTime.now()`
위 코드로 변경하였고 postman으로 테스트 해보았을 때 버디 신청 금지되는 사항까지 구현 테스트 완료하였습니다.

2024-02-25 17:34 UTC, swandevson requested changes
리뷰 사항 수정부탁드립니다!

2024-02-25 17:34 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
> +	Optional<BuddyMatched> findLatestByOwnerOrPartner(@Param("owner") Buddy owner);
최근 한 명만 가져와야하니 LIMIT 1이 있어야하지 않을가요?

2024-02-25 17:34 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
>  	Optional<BuddyMatched> findByOwnerAndPartner(Buddy owner, Buddy partner);
owner와 partner의 순서가 바뀔 경우도 고려해야하지 않을까요?
버디 A, B가 있다고 할 때 A가 owner에 있을 것이라는 보장이 없습니다

2024-02-25 17:34 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			latestBuddy.getUpdatedAt().plusHours(1).isAfter(LocalDateTime.now())) {
`isAfter`보다 `isBefore`를 쓰면 어떨까하는 생각에 이전 리뷰 내용을 작성한 것이었습니다!
isBefore가 좀 더 가독성이 좋지 않을까 싶습니다

2024-02-25 17:34 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
>  			buddyMatched.setStatus(BuddyMatchedStatus.MATCHING_FAIL);
혹시 `@Setter` 어노테이션을 사용하셨나요? 엔티티에서 `@Setter`는 절대 사용하시면 안됩니다! (무분별한 변경 위험성 있음)
메소드로 따로 선언하시고, `setStatus`보다 `changeStatus`같이 좀 더 의미있는 네이밍을 사용해주세요

2024-02-25 17:34 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +		targetBuddy.changeStatus(BuddyStatus.MATCHING_COMPLETED);
private 메소드로 따로 빼서 리팩토링 하는 방법도 좋을 것 같습니다

2024-02-25 17:34 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/dto/request/MatchingResultRequest.java
> +) { }
boolean이 아닌 status로 request를 받을 때의 이점이 있을까요?
프론트측에서 추가적으로 enum을 또 선언해줘야해서 작업이 더 필요할 것 같습니다

2024-02-25 17:34 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
>  		List<Buddy> ownerBuddies = buddyRepository.findAllByMemberOrderByCreatedAtDesc(owner);
전체를 찾아올 이유가 있을까요? 가장 최근 버디 중, IN_PROGRESS 상태인것만 찾으면 될 것 같습니다

2024-02-25 23:16 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
> +	Optional<BuddyMatched> findLatestByOwnerOrPartner(@Param("owner") Buddy owner);
BY bm.id DESC 이후에 LIMIT 1을 추가함으로써 한 건만 가져올 수 있도록 수정하였습니다.

2024-02-25 23:24 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
>  	Optional<BuddyMatched> findByOwnerAndPartner(Buddy owner, Buddy partner);
(bm.owner = :owner OR bm.partner = :owner) 해당 쿼리문을 추가해서 owner와 partner의 역할이 바뀌더라도 두 열 중 어느 한쪽이라도 owner와 일치하는 경우를 찾도록 수정하였습니다.

2024-02-25 23:51 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			latestBuddy.getUpdatedAt().plusHours(1).isAfter(LocalDateTime.now())) {
`LocalDateTime.now().isBefore(latestBuddy.getUpdatedAt().plusHours(1))` 
이렇게 보다 직관적으로 와닿을 수 있도록 수정하였습니다.

2024-02-25 23:59 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
>  			buddyMatched.setStatus(BuddyMatchedStatus.MATCHING_FAIL);
set 방식이 아니라 MatchingScheduler에서 짝매칭이 된 이후에 change 메소드를 Buddy 엔티티에 따로 정의하신 부분을 참고하여 수정 완료하였습니다. 알려주셔서 감사드립니다!

2024-02-26 00:02 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
> +		targetBuddy.changeStatus(BuddyStatus.MATCHING_COMPLETED);
`handlerBuddyMatchedSuccess` 이 함수를 하나 만들어 분리하였습니다.

2024-02-26 00:20 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
>  		List<Buddy> ownerBuddies = buddyRepository.findAllByMemberOrderByCreatedAtDesc(owner);
```
List<Buddy> ownerBuddies = buddyRepository.findAllByMemberOrderByCreatedAtDesc(owner);
Buddy ownerLatestBuddy = ownerBuddies.isEmpty() ? null : ownerBuddies.get(0);
```
Member owner에 대해 모든 버디를 찾고 그 중 가장 최근 것을 찾는 로직보다 아래와 같이 

```
Optional<Buddy> optionalOwnerLatestBuddy = buddyRepository.findTopByMemberAndStatusOrderByCreatedAtDesc(owner, BuddyStatus.IN_PROGRESS);
Buddy ownerLatestBuddy = optionalOwnerLatestBuddy.orElseThrow(() -> new CustomException(ErrorCode.BUDDY_NOT_FOUND));
```
상태를 기준으로 가장 최근 것을 찾는 것이 더 효율적인 것 같다고 느꼈습니다. 피드백 감사드립니다.

2024-02-26 00:33 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/dto/request/MatchingResultRequest.java
> +) { }
백엔드 측에서 이미 상태가 enum으로 정의되어있으니 프론트 분들께서 해당 상태값을 다이렉트로 넘기는 방식보다는 짝 수락에 대해 true, false를 넘기고 백엔드 단에서 상태를 그에 따라 불러오는 방식이 더 좋을 것 같습니다. 좋은 피드백 감사드립니다.

2024-02-26 05:57 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			.orElse(null);
저 부분은 저가 작성한 코드였었는데 ElseThrow가 아닌 orElse로 해야할 것 같습니다! ElseThrow로 했을 경우에는 해당 멤버가 처음으로 버디를 등록할 때 오류가 발생합니다.
첫 버디 등록시에는 latestbuddy가 없는 상태로 등록을 해야하는데 ElseThrow로 한다면 등록을 진행하지않고 예외를 던져버리기 때문에 orElse로 해야할 것 같스비낟

2024-02-26 06:07 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			.orElse(null);
@rong5026 영환님께서 latestBuddy에 대해서 작성하셨던 코드는 아래이고
```
Buddy latestBuddy = getLastBuddyByMemberId(memberId)
			.orElseThrow(() -> new CustomException(ErrorCode.BUDDY_NOT_FOUND));
```

제가 거절 패널티를 부여하기 위해서
```
Buddy latestBuddy = buddyRepository.findTopByMemberOrderByUpdatedAtDesc(member)
		.orElseThrow(() -> new CustomException(ErrorCode.BUDDY_NOT_FOUND));

if (latestBuddy != null && latestBuddy.getStatus() == BuddyStatus.REJECT &&
         LocalDateTime.now().isBefore(latestBuddy.getUpdatedAt().plusHours(1))) {
         throw new CustomException(ErrorCode.REJECT_PENALTY);
}
```
위 코드를 추가했었씁니다. 변수명이 똑같아서 헷갈리셨을 것 같습니다.

2024-02-26 07:02 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			.orElse(null);
@rong5026 예외 처리를 하는 쪽으로 수정을 했었는데 말씀해주신 부분에 대해 테스트를 해봤을 때 throw로 던져버려서 첫 버디 등록이 안되는 오류가 있음을 확인했습니다. 수정했고 놓친 부분에 대해 말씀해주셔서 감사드립니다!

2024-02-26 07:09 UTC, rong5026 reviewed
그리구 register함수안에서 public void registerBuddy(RegisterRequest request, String memberId) {
		Member member =
			memberRepository
				.findById(memberId)
				.orElseThrow(() -> new CustomException(ErrorCode.MEMBER_NOT_FOUND));

		checkPossibleRegistration(memberId);

		Buddy buddy = createBuddyEntity(request, member);
		buddyRepository.save(buddy);
	}
 이미 checkPossibleRegistration 이 함수에서 패널티까지 체크를 하고 있어서 저 부분의 코드는 없어도 될 것 같습니다!

2024-02-26 07:14 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +			.orElse(null);
저는 처음 버디 신청을 할 때 REJECT 상태이고 update 시간이 현재 시간보다 1시간 이내로 작을 때 버디를 신청 못하게 해야하니까 registerBuddy에 패널티 로직을 추가해야 한다고 생각했습니다. 아래 중복된 기능을 하는 코드가 있으니 지우도록 할게요

2024-02-26 07:58 UTC, rla124 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
>  	Optional<BuddyMatched> findByOwnerAndPartner(Buddy owner, Buddy partner);
A가 owner, B가 partner인 경우와 B가 owner, A가 partner인 경우 모두 검색하는 쿼리문을 추가하였습니다.

2024-02-26 13:24 UTC, swandevson approved these changes
LGTM

2024-02-26 14:12 UTC, merged