✨ Buddy, BuddyMatched가 Complete일 때 응답 메소드 구현
SejongPeer/SejongPeer-back pull request #79
Opened 2024-02-27 07:31 UTC by rong5026

## 🌱 관련 이슈
- #73 

## 📌 작업 내용 및 특이사항
- 버디 매칭 후 상대방 정보 요청
- 버디 매칭 수락 완료 후 상대방 정보 요청
- BuddyMatchingService에 findTargetBuddy 공통으로 쓰이는 함수 리펙토링

## 📝 참고사항
- BuddyService에서 BuddyMatchingServiced의 함수를 쓰려고
- '''private final MatchingService matchingService;
	private final BuddyRepository buddyRepository;
	private final MemberRepository memberRepository;
	private final BuddyMatchingService buddyMatchingService;''' 이런식으로 

buddyService에서 BuddyMatchingService를 불러와서 사용을 했는데 더 좋은 방법이 있을까요,,?  
찾아보니 나중에 서로 참조를 하게 되는 경우가 생기면 순환참조 문제가 발생할 수 있다고 하긴하는데 다른 방법을 찾지못해서 여쭤봅니다!

## 📚 기타
-

2024-02-28 16:51 UTC, swandevson requested changes
리뷰 사항 확인 부탁드립니다!

2024-02-28 16:51 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
> +	@Operation(summary = "버디 매칭 후 상대방 정보요청", description = "매칭 후 상대방의 정보 리턴")
"버디 매칭 후"보다는 "버디 수락/거절 창에서의 상대방 정보 요청"이 맥락상 덜 헷갈리 것 같습니다

2024-02-28 16:51 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/PartnerInfoResponse.java
> +public record PartnerInfoResponse(
`CompletedPartnerInfoResponse`와 확실히 구분짓기 위해 `MatchingPartenerInfoResposne`처럼 현재 수락/거절 창에서 뜨는 상대방의 정보라는 의미가 더 강하게 나타났으면 좋겠습니다

2024-02-28 16:51 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
>  	}
`ifPresent` 내부에 다시 if로 들어가는 부분이 가독성을 해치는 것 같습니다.
Optional로 따로 변수를 받고 관리하는 것이 더 좋을 것 같습니다!

2024-02-28 16:51 UTC, swandevson commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +		));
해당 부분은 `PartnerInfoResponse`에 `from` 정적 메소드를 선언해 `partnerMember`를 인자로받고 새로운 객체를 생성해주는 방향이 더 좋아보입니다

2024-02-28 16:55 UTC, swandevson commented
말씀하신 서비스끼리 의존성이 생기는 부분은 우선 순환참조는 되지 않으니 괜찮은 것 같습니다. 오히려 한 곳에 몰려있는 것보다 지금처럼 나누신게 더 좋아보입니다!

배포 후 이부분은 한 번 토의하고 리팩토링 해보면 좋을 것 같습니다

2024-02-29 00:25 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
> +	@Operation(summary = "버디 매칭 후 상대방 정보요청", description = "매칭 후 상대방의 정보 리턴")
네넵!

2024-02-29 00:27 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/PartnerInfoResponse.java
> +public record PartnerInfoResponse(
넵 수정했습니다

2024-02-29 00:37 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
>  	}
Optional<Buddy> optionalBuddy = getLastBuddyByMemberId(memberId);

		optionalBuddy.ifPresent(latestBuddy -> {
			if (latestBuddy.getStatus() == BuddyStatus.IN_PROGRESS) {
				throw new CustomException(ErrorCode.REGISTRATION_NOT_POSSIBLE);
			}
			if (latestBuddy.getStatus().equals(BuddyStatus.REJECT) &&
				!isPossibleFromUpdateAt(latestBuddy.getUpdatedAt())) {
				throw new CustomException(ErrorCode.REJECT_PENALTY);
			}
		});
"Optional로 따로 변수를 받고 관리하는 것".저가 이부분을 잘이해를 못했는데 다시 설명해주실 수 있으실까요??

optionalBuddy의 값이 null이라면 바로 아무예외도 뱉지않고 버디 정상등록이 되도록 하고, 값이 있다면 패널티 체크를 하도록 했는데 ifPresent안 체크 부분들을 함수로 따로 빼면은 괜찮을까요?

2024-02-29 00:45 UTC, rong5026 commented on src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
> +		));
네넵!

2024-02-29 11:00 UTC, merged